import { Bebas_Neue, Red_Hat_Display, Courier_Prime } from "next/font/google";
import Head from "next/head";
import Footer from "./footer";
import "./globals.css";
import Cursor from "./components/cursor_cerchio";

const bebasNeue = Bebas_Neue({ subsets: ["latin"], weight: "400" });
const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});
const courierPrime = Courier_Prime({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Matteo Beu | Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
      </Head>
      <body className={courierPrime.className}>
        <Cursor />
        {children}
        <Footer />
      </body>
    </html>
  );
}
